kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-mysql-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-statefullset-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-mysql-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-statefullset-data-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi


kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-mysql-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-statefullset-data-2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi      